# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-OSM-Tiles
version:      0.02
version_from: lib/Geo/OSM/Tiles.pm
installdirs:  site
requires:
    Cwd:                           0
    File::Basename:                0
    File::Find:                    0
    File::Path:                    0
    File::Temp:                    0
    Getopt::Long:                  0
    LWP:                           0
    Math::Trig:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
